openapi: 3.0.1
info:
  title: 小程序搜索API
  description: 剧本搜索相关API接口定义
  version: 1.0.0

servers:
  - url: https://unicloud.dcloud.net.cn
    description: uniCloud生产环境

paths:
  /listScripts:
    get:
      summary: 获取剧本列表（支持搜索）
      description: 获取剧本分页列表，支持按关键词搜索所有剧本内容
      operationId: listScripts
      parameters:
        - name: page
          in: query
          description: 页码，从1开始
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          description: 每页条数
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 12
        - name: q
          in: query
          description: 搜索关键词，支持剧本标题和作者搜索
          required: false
          schema:
            type: string
            minLength: 1
            maxLength: 50
        - name: sortBy
          in: query
          description: 排序字段
          required: false
          schema:
            type: string
            enum: [createdAt, updateTime, likes, usageCount]
            default: createdAt
      responses:
        '200':
          description: 成功响应
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 0
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Script'
                  total:
                    type: integer
                    description: 总记录数
                    example: 156
                required:
                  - code
                  - data
        '400':
          description: 参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Script:
      type: object
      properties:
        id:
          type: string
          description: 剧本ID
          example: "507f1f77bcf86cd799439011"
        title:
          type: string
          description: 剧本标题
          example: "推理之谜"
        author:
          type: string
          description: 作者姓名
          example: "张三"
        version:
          type: string
          description: 版本号
          example: "1.0.0"
        likes:
          type: integer
          description: 点赞数
          example: 42
        images:
          type: array
          items:
            type: string
          description: 剧本图片URL数组
          example: ["https://example.com/image1.jpg"]
        status:
          type: string
          description: 剧本状态
          enum: [active, inactive, published, draft, archived]
          example: "active"
        tags:
          type: array
          items:
            type: string
          description: 标签数组
          example: ["推理", "悬疑"]
        createdAt:
          type: string
          format: date-time
          description: 创建时间
        updateTime:
          type: string
          format: date-time
          description: 更新时间
        usageCount:
          type: integer
          description: 使用次数
          example: 128
      required:
        - id
        - title
        - author

    Error:
      type: object
      properties:
        code:
          type: integer
          example: -1
        errMsg:
          type: string
          description: 错误信息
          example: "参数错误：页码必须大于0"