openapi: 3.0.3
info:
  title: 投稿须知UI组件规范
  description: 投稿须知界面的组件接口和样式规范
  version: 1.0.0
  contact:
    name: 开发团队

servers:
  - url: https://uniapp.dcloud.net.cn
    description: uni-app小程序环境

paths: {}

components:
  schemas:
    TitleSection:
      type: object
      required:
        - text
        - level
      properties:
        text:
          type: string
          description: 标题文字内容
          example: "投稿须知"
        level:
          type: integer
          enum: [1, 2, 3]
          description: 标题层级，影响字体大小
          example: 1
        style:
          type: object
          description: 自定义样式覆盖
          properties:
            fontSize:
              type: string
              example: "32rpx"
            color:
              type: string
              example: "#333"

    ParagraphSection:
      type: object
      required:
        - text
      properties:
        text:
          type: string
          description: 段落文字内容
          example: "欢迎您参与血染钟楼剧本创作！"
        emphasis:
          type: boolean
          description: 是否强调显示
          default: false
          example: true
        style:
          type: object
          description: 自定义样式覆盖

    ListItem:
      type: object
      required:
        - content
      properties:
        content:
          type: string
          description: 列表项内容
          example: "剧本必须为原创作品，不得侵犯他人版权"
        emphasis:
          type: boolean
          description: 是否强调显示
          default: false
        link:
          type: string
          description: 可选的链接地址
          example: "mailto:contact@example.com"

    OrderedList:
      type: object
      required:
        - items
      properties:
        title:
          type: string
          description: 列表标题
          example: "投稿要求"
        items:
          type: array
          items:
            $ref: '#/components/schemas/ListItem'
          minItems: 1
        startNumber:
          type: integer
          description: 起始编号
          default: 1
          minimum: 1

    UnorderedList:
      type: object
      required:
        - items
      properties:
        title:
          type: string
          description: 列表标题
          example: "投稿格式要求"
        items:
          type: array
          items:
            $ref: '#/components/schemas/ListItem'
          minItems: 1
        bulletStyle:
          type: string
          enum: ["circle", "square", "disc"]
          description: 项目符号样式
          default: "circle"

    ContactSection:
      type: object
      required:
        - title
        - content
      properties:
        title:
          type: string
          description: 联系方式标题
          example: "投稿邮箱"
        content:
          type: string
          description: 联系信息内容
          example: "contact@example.com"
        type:
          type: string
          enum: ["email", "phone", "url"]
          description: 联系方式类型
          default: "email"

    PageContent:
      type: object
      required:
        - title
        - sections
      properties:
        title:
          type: string
          description: 页面标题
          example: "投稿须知"
        sections:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/TitleSection'
              - $ref: '#/components/schemas/ParagraphSection'
              - $ref: '#/components/schemas/OrderedList'
              - $ref: '#/components/schemas/UnorderedList'
              - $ref: '#/components/schemas/ContactSection'
          description: 页面内容区块数组
        metadata:
          type: object
          description: 页面元数据
          properties:
            version:
              type: string
              example: "1.0.0"
            lastUpdated:
              type: string
              format: date
              example: "2024-01-16"
            author:
              type: string
              example: "开发团队"

  responses:
    RenderSuccess:
      description: 组件渲染成功
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              rendered:
                type: boolean
                example: true
              componentId:
                type: string
                example: "title-section-1"

    RenderError:
      description: 组件渲染失败
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: string
                example: "无效的组件类型"
              componentType:
                type: string
                example: "unknown-type"